export const metadata = {
  title: "Posts Page",
  description: "Generated by create next app",
}

import pg from 'pg'
import myImage from '@/../public/cat.jpeg'
import Image from "next/image"
import TitleAnimation from '@/app/components/TitleAnimation'
import {AnimateIn} from '@/app/components/AnimateIn'
import ExitAnimation from '../components/ExitAnimation'


export default async function PostsPage(){
    const db = new pg.Pool({
        connectionString: process.env.NEXT_PUBLIC_DATABASE_URL,
    });

    const posts = (await db.query('SELECT * FROM postworkshop')).rows;

    //console.log(posts);
    //throw new Error("I deliberately broke this page"); ///////////////////////////////////

    return (
        <div className='flex flex-col items-center'>
            <div className='max-w-5xl flex-col text-shadow-white bg-red-900 justify-center'>
                <h1 className='text-sky-800 bg-amber-400'>Posts</h1>
                <ul className='text-sky-300 flex flex-col text-center m-3 p-2'>
                    {posts.map((post) => (
                        <li key={post.id}>{post.title}</li>
                    ))}
                </ul>
            </div>
            <TitleAnimation/>
            <ExitAnimation/>
            <Image src={myImage} alt="cat image" height={200} width={"auto"} placeholder="blur" />
            <AnimateIn>
                <Image src={'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%2Fid%2FOIP.K89tEAe4xWnlr2Szk_IusAHaJQ%3Fpid%3DApi%26defcache%3D1&f=1&ipt=0490868f9b31604f4ade9a25599f1496ddcc9af3de752b548df8a06fe6265615&ipo=images'} alt='cat image' width={200} height={200}/>
            </AnimateIn>
        </div>
    );
}