export const metadata = {
  title: "Form Page",
  description: "Generated by create next app",
}

import {db} from '@/utils/dbConnection'
import {redirect} from 'next/navigation'
import {revalidatePath} from 'next/cache'
import styleValues from './postPage.module.css'

export default function NewPost(){
    
    async function handleSave(formData){
        "use server";
        const formValues = {
            title: formData.get('title'),
            content: formData.get('content')
        }
        db.query('INSERT INTO postworkshop (title, content) VALUES ($1, $2)', 
            [formValues.title, formValues.content]
        );
        console.log('Saved data');
        revalidatePath('/posts');
        redirect('/posts');
    }
    
    return(
        <form className='flex flex-col items-center' action={handleSave}>
            <h1 className='text-sky-300 border-t-orange-700'>Form</h1>
            <label htmlFor='title'>Title</label>
            <input className='bg-amber-400 rounded-md p-1' id='title' name='title' type='text' />
            <label htmlFor='content'>Content</label>
            <textarea className='bg-amber-400 rounded-md p-1' id='content' name='content'/>
            <button type='submit'>Save</button>
        </form>
    )
}